os:
  - linux
  - osx
dist: precise
sudo: false
language: rust
cache: cargo
addons:
  apt:
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - libgpgme11-dev
env:
  global:
    - GPGME_DEBUG=9
    - AUTOMAKE_VERSION=1.14.1
    - GETTEXT_VERSION=0.19.3
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5     ; fi
