os:
  - linux
  - osx
dist: trusty
sudo: false
language: rust
cache: rust
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - libgpgme11-dev
      - libgpg-error-dev
      - gcc-4.9
      - g++-4.9

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5     ; fi
