os:
  - linux
  - osx

dist: trusty
sudo: false
language: rust
addons:
  apt:
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - libgpgme11-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5     ; fi
