language: rust
cache: cargo
script:
  - cargo test --all --locked
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - libgpgme11-dev
      - libgpg-error-dev
      - libgtk-3-dev
      - gcc-4.9
      - g++-4.9
matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      env:
        - CC=/usr/bin/gcc-4.9
        - CXX=/usr/bin/g++-4.9
    - os: osx
      before_install:
        - brew update
        - brew install qt5
        - brew unlink python@2
        - brew install gtk+3
        - brew install gpgme
