[package]
name = "ripasso"
version = "0.0.1"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com"]

[features]
default = ["qml"]
use-gtk = ["gtk"]
use-qml = ["qml"]
use-tui = ["cursive"]

[dependencies]
qml = { git = "https://github.com/White-Oak/qml-rust", optional = true }
gtk = { version = "0.4.0", features = ["v3_10"], optional = true }
glib = "0.5.0"
cursive = { version = "0.8.1", optional = true }
notify = "4.0.3"
glob = "0.2.11"
clipboard =  "0.4.6"
gpgme = { version = "0.7.2", "default-features" = false }
chrono = "0.4"
git2 = "0.6"
error-chain = "0.11.0"
log = "0.4.0"
env_logger = "0.5.6"
pad = "0.1.5"

[dev-dependencies]
tempdir = "0.3"
