[package]

name = "ripasso"
version = "0.0.1"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com"]

[dependencies]
gtk = "0.2.0"
notify = "4.0.0"
glob = "0.2.11"
clipboard = "0.3.0"
gpgme = { git = "https://github.com/johnschug/rust-gpgme", branch = "master" }

[features]
#default = ["gtk_3_22"]
gtk_3_10 = ["gtk/v3_10"]
