[package]
name = "ripasso"
description = "A password manager that uses the file format of the standard unix password manager 'pass'"
repository = "https://github.com/cortex/ripasso/"
keywords = ["password-manager", "pass"]
version = "0.6.0-alpha"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com", "Alexander Kjäll <alexander.kjall@gmail.com>"]
license = "GPL-3.0-only"
edition = '2018'

[dependencies]
glob = "0.3.0"
gpgme = "0.9.2"
chrono = "0.4"
git2 = "0.13.12"
rand = "0.7.3"
whoami = "1.0.0"
toml = "0.5.7"

[dependencies.config]
version = "0.10.1"
default-features = false
features = ["toml"]

[dev-dependencies]
tempfile = "3.1.0"
flate2 = "1.0.19"
tar = "0.4.30"
criterion = "0.3.3"

[workspace]

members = [
    "gtk", "qml", "cursive"
]

[[bench]]
name = "library_benchmark"
harness = false

