[package]

name = "ripasso"
version = "0.0.1"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com"]

[dependencies]
gtk = {version = "0.2.0", features = ["v3_10"]}
qml = { git = "https://github.com/White-Oak/qml-rust" }
glib = "0.3.1"
notify = "4.0.2"
glob = "0.2.11"
clipboard = "0.3.0"
gpgme = {version = "0.6.1", "default-features" = false }
