[package]
name = "ripasso-gtk"
version = "0.5.0-alpha"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>"]
edition = '2018'

[dependencies]
ripasso = { path = "../"}
gtk = { version = "0.8.1", features = ["v3_16"] }
glib = "0.9.3"
