[package]
name = "ripasso-gtk"
version = "0.7.0-alpha"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>"]
edition = '2021'

[dependencies]
ripasso = { path = "../", version = "0.7.0-alpha" }
gtk = { version = "0.15.5", features = ["v3_22"] }
gdk = "0.15.4"
glib = "0.15.12"
lazy_static = "1.4.0"
cli-clipboard = "0.4.0"
